# Generated by Django 3.1.1 on 2021-01-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaningModel',
            new_name='LearningModel',
        ),
    ]
