# Generated by Django 3.1.1 on 2021-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210104_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='training_interval',
            field=models.SmallIntegerField(default=1),
        ),
    ]
