# Generated by Django 3.1.1 on 2021-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20210105_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktable',
            name='training_date',
            field=models.DateTimeField(verbose_name='training date'),
        ),
    ]
